#!/usr/bin/env python3
"""
Mountainfish Profile Generator
根据分析结果生成 mf_style.yaml 配置文件
"""

import sys
import json
from pathlib import Path
from typing import Dict


def dict_to_yaml(data: dict, indent: int = 0) -> str:
    """将字典转换为 YAML 格式字符串"""
    lines = []
    for key, value in data.items():
        prefix = "  " * indent
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            lines.append(dict_to_yaml(value, indent + 1))
        elif isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                lines.append(f"{prefix}  - {item}")
        else:
            lines.append(f"{prefix}{key}: {value}")
    return "\n".join(lines)


def generate_profile(report: Dict, output_path: str = 'mf_style.yaml') -> bool:
    """生成 mf_style.yaml 配置文件"""
    try:
        # 从报告中提取配置
        profile = {
            'mountainfish_style': {
                'version': '1.0.0',
                'generated_by': 'Mountainfish Skill Analyzer',
                'language': 'C/C++'
            },
            'naming': {
                'functions': map_naming_style(report.get('naming', {}).get('functions', 'unknown')),
                'variables': map_naming_style(report.get('naming', {}).get('variables', 'unknown')),
                'classes': map_naming_style(report.get('naming', {}).get('classes', 'unknown')),
                'constants': map_naming_style(report.get('naming', {}).get('constants', 'unknown'))
            },
            'formatting': {
                'indent': map_indent_style(report.get('indentation', 'unknown')),
                'indent_width': get_indent_width(report.get('indentation', 'unknown')),
                'brace_style': map_brace_style(report.get('brace_style', 'unknown')),
                'max_line_length': 100,
                'space_before_paren': 'ControlStatements',
                'space_after_cast': True
            },
            'patterns': {
                'error_handling': 'return_error_code',
                'logging': 'custom_macro',
                'memory_management': 'manual',
                'header_guards': 'pragma_once'
            },
            'preferences': {
                'language': 'C',
                'compiler': 'GCC',
                'standard': 'C11',
                'build_system': 'CMake'
            },
            'comments': {
                'style': 'doxygen',
                'line_comment': '//',
                'block_comment': '/** */',
                'todo_format': 'TODO(username): description'
            }
        }

        # 写入 YAML 文件
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Generated by Mountainfish Skill Analyzer\n")
            f.write("# Style configuration based on code analysis\n\n")
            f.write(dict_to_yaml(profile))

        print(f"\n[OK] Generated style config: {output_path}")
        return True

    except Exception as e:
        print(f"[ERROR] Failed to generate config: {e}", file=sys.stderr)
        return False


def map_naming_style(detected: str) -> str:
    """映射命名风格"""
    mapping = {
        'snake_case': 'snake_case',
        'camelCase': 'camelCase',
        'PascalCase': 'PascalCase',
        'UPPER_SNAKE_CASE': 'UPPER_SNAKE_CASE',
        'unknown': 'snake_case'  # 默认 snake_case
    }
    return mapping.get(detected, 'snake_case')


def map_indent_style(detected: str) -> str:
    """映射缩进风格"""
    mapping = {
        '4_spaces': 'space',
        '2_spaces': 'space',
        'tab': 'tab',
        'mixed': 'space',
        'unknown': 'space'
    }
    return mapping.get(detected, 'space')


def get_indent_width(detected: str) -> int:
    """获取缩进宽度"""
    mapping = {
        '4_spaces': 4,
        '2_spaces': 2,
        'tab': 4,  # Tab 通常相当于 4 个空格
        'mixed': 4,
        'unknown': 4
    }
    return mapping.get(detected, 4)


def map_brace_style(detected: str) -> str:
    """映射大括号风格"""
    mapping = {
        'K&R': 'attach',
        'Allman': 'allman',
        'mixed': 'attach',
        'unknown': 'attach'
    }
    return mapping.get(detected, 'attach')


def generate_clang_format(profile_path: str, output_path: str = '.clang-format') -> bool:
    """根据 mf_style.yaml 生成 .clang-format 配置"""
    try:
        # 简单解析 YAML 文件
        profile = {}
        current_section = None
        current_dict = profile

        with open(profile_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.rstrip()
                if not line or line.startswith('#'):
                    continue

                # 计算缩进级别
                indent = len(line) - len(line.lstrip())
                content = line.strip()

                if ':' in content:
                    key, _, value = content.partition(':')
                    key = key.strip()
                    value = value.strip()

                    if indent == 0:
                        current_section = key
                        profile[key] = {}
                        current_dict = profile[key]
                    elif indent == 2 and current_section:
                        if value:
                            current_dict[key] = value
                        else:
                            current_dict[key] = {}

        formatting = profile.get('formatting', {})
        brace_style = formatting.get('brace_style', 'attach')

        # 生成 .clang-format 内容
        clang_format = f"""# Generated by Mountainfish Skill
# Style Profile: {profile_path}

---
Language: Cpp
BasedOnStyle: LLVM

# 缩进配置
IndentWidth: {formatting.get('indent_width', 4)}
TabWidth: {formatting.get('indent_width', 4)}
UseTab: {'Always' if formatting.get('indent') == 'tab' else 'Never'}
IndentCaseLabels: true
IndentPPDirectives: None
NamespaceIndentation: None

# 大括号配置
BreakBeforeBraces: {map_brace_to_clang(formatting.get('brace_style', 'attach'))}
AllowShortBlocksOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false

# 行宽配置
ColumnLimit: {formatting.get('max_line_length', 100)}

# 空格配置
SpaceBeforeParens: {formatting.get('space_before_paren', 'ControlStatements')}
SpaceAfterCStyleCast: {'true' if formatting.get('space_after_cast', True) else 'false'}
SpacesInParentheses: false

# 对齐配置
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands: true
AlignTrailingComments: true

# 其他配置
AllowAllParametersOfDeclarationOnNextLine: true
BinPackArguments: true
BinPackParameters: true
BreakConstructorInitializersBeforeComma: false
BreakStringLiterals: true
SortIncludes: true
IncludeBlocks: Preserve

# 注释配置
ReflowComments: true
"""

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(clang_format)

        print(f"[OK] Generated .clang-format: {output_path}")
        return True

    except Exception as e:
        print(f"[ERROR] Failed to generate .clang-format: {e}", file=sys.stderr)
        return False


def map_brace_to_clang(brace_style: str) -> str:
    """映射大括号风格到 clang-format 配置"""
    mapping = {
        'attach': 'Attach',
        'allman': 'Allman',
        'gnu': 'GNU',
        'webkit': 'WebKit',
        'linux': 'Linux'
    }
    return mapping.get(brace_style, 'Attach')


def _setup_encoding():
    """修复 Windows 下 GBK 编码问题"""
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def main():
    """主函数"""
    _setup_encoding()
    if len(sys.argv) < 2 or sys.argv[1] in ("--help", "-h", "help"):
        print("Mountainfish Profile Generator — 根据分析结果生成 mf_style.yaml 和 .clang-format")
        print()
        print("用法: python profile_generator.py <报告JSON文件> [--clang-format]")
        print()
        print("参数:")
        print("  <报告JSON文件>   由 analyzer.py --json 输出的 JSON 报告文件")
        print("  --clang-format   同时生成 .clang-format 文件")
        print()
        print("示例:")
        print("  python profile_generator.py report.json")
        print("  python profile_generator.py report.json --clang-format")
        sys.exit(0)

    report_file = sys.argv[1]
    generate_clang = '--clang-format' in sys.argv

    # 读取报告
    import json
    with open(report_file, 'r', encoding='utf-8') as f:
        report = json.load(f)

    # 生成 mf_style.yaml
    if generate_profile(report):
        if generate_clang:
            generate_clang_format('mf_style.yaml')


if __name__ == '__main__':
    main()
